[tool.poetry]
name = "pybash"
version = "0.1.0"
description = ""
authors = ["yaroslav2k <iaroslav2k@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
black = "^22.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
